# Compile acpi/dsdt.asl -> dsdt.aml -> dsdt_aml.h (a C byte array).
#
# Run this after ANY edit to dsdt.asl, then rebuild Hypervisor.c. The generated
# header is committed so a build does not require iasl, but the .asl remains the
# source of truth -- never hand-edit dsdt_aml.h.
#
# iasl is Intel's ACPI compiler (ACPICA). Get it from the official releases:
#   https://github.com/acpica/acpica/releases  ->  iasl-win-<date>.zip
# Set IASL to point at it, or drop iasl.exe next to this script.

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

$iasl = $env:IASL
if (-not $iasl) { $iasl = "C:\LocalHost-evidence\tools\iasl\iasl.exe" }
if (-not (Test-Path $iasl)) {
    if (Test-Path "$PSScriptRoot\iasl.exe") { $iasl = "$PSScriptRoot\iasl.exe" }
    else { throw "iasl.exe not found. Set `$env:IASL or place iasl.exe in acpi\. See header comment." }
}

Write-Host "compiling dsdt.asl with $iasl"
$out = & $iasl dsdt.asl 2>&1
$out | Select-String -Pattern 'AML Output|Compilation|Error|Warning' | ForEach-Object { Write-Host "  $($_.Line)" }
if (-not (Test-Path "dsdt.aml")) { throw "iasl produced no dsdt.aml" }

$b = [System.IO.File]::ReadAllBytes("dsdt.aml")

# Sanity-check the produced table before we bake it into the hypervisor: a bad
# DSDT surfaces as an opaque 0xA5 ACPI_BIOS_ERROR at guest boot, which is far
# more expensive to diagnose than failing loudly right here.
$sig = [System.Text.Encoding]::ASCII.GetString($b[0..3])
if ($sig -ne "DSDT") { throw "bad signature '$sig' (expected DSDT)" }
$lenField = [BitConverter]::ToUInt32($b, 4)
if ($lenField -ne $b.Length) { throw "length field $lenField != file size $($b.Length)" }
$sum = 0; foreach ($x in $b) { $sum = ($sum + $x) -band 0xFF }
if ($sum -ne 0) { throw ("checksum invalid: bytes sum to 0x{0:X2}, expected 0x00" -f $sum) }
Write-Host "  validated: signature=DSDT length=$($b.Length) checksum OK"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// GENERATED by acpi/build_dsdt.ps1 from acpi/dsdt.asl -- DO NOT EDIT BY HAND.")
[void]$sb.AppendLine("// Edit dsdt.asl and re-run the script instead.")
[void]$sb.AppendLine("//")
[void]$sb.AppendLine("// Complete DSDT table: 36-byte ACPI header followed by the AML definition")
[void]$sb.AppendLine("// block. iasl emits the header itself, so this is embedded whole -- do NOT")
[void]$sb.AppendLine("// call acpiPutHeader() over it. The loader still recomputes the checksum")
[void]$sb.AppendLine("// after OVMF patches addresses, which is why the byte at offset 9 may differ")
[void]$sb.AppendLine("// from the value here.")
[void]$sb.AppendLine("#define DSDT_AML_SIZE $($b.Length)")
[void]$sb.AppendLine("static const unsigned char dsdtAml[DSDT_AML_SIZE] = {")
for ($i = 0; $i -lt $b.Length; $i += 12) {
    $end = [Math]::Min($i + 11, $b.Length - 1)
    $line = ($b[$i..$end] | ForEach-Object { "0x{0:X2}," -f $_ }) -join " "
    [void]$sb.AppendLine("    $line")
}
[void]$sb.AppendLine("};")

[System.IO.File]::WriteAllText("$PSScriptRoot\dsdt_aml.h", $sb.ToString())
Write-Host "wrote dsdt_aml.h ($($b.Length) bytes of AML)"
